In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import datetime as datetime
import matplotlib.dates as mdates
import edgar_utils as eu

In [2]:
%load_ext autoreload
%autoreload 2

In [334]:
jj = eu.get_json_financials_from_tikr('AAPL')

In [394]:
jj[(jj.tag.isin(["Revenues", "RevenueFromContractWithCustomerExcludingAssessedTax"]))]

,end,val,accn,fy,fp,form,filed,frame,tag,units,start
17648,2017-09-30,2.292340e+11,0000320193-19-000119,2019,FY,10-K,2019-10-31,CY2017,RevenueFromContractWithCustomerExcludingAssess...,USD,2016-09-25
17649,2017-12-30,8.829300e+10,0000320193-19-000010,2019,Q1,10-Q,2019-01-30,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2017-10-01
17650,2017-12-30,8.829300e+10,0000320193-19-000119,2019,FY,10-K,2019-10-31,CY2017Q4,RevenueFromContractWithCustomerExcludingAssess...,USD,2017-10-01
17651,2018-03-31,1.494300e+11,0000320193-19-000066,2019,Q2,10-Q,2019-05-01,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2017-10-01
17652,2018-03-31,6.113700e+10,0000320193-19-000066,2019,Q2,10-Q,2019-05-01,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2017-12-31
17653,2018-03-31,6.113700e+10,0000320193-19-000119,2019,FY,10-K,2019-10-31,CY2018Q1,RevenueFromContractWithCustomerExcludingAssess...,USD,2017-12-31
17654,2018-06-30,2.026950e+11,0000320193-19-000076,2019,Q3,10-Q,2019-07-31,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2017-10-01
17655,2018-06-30,5.326500e+10,0000320193-19-000076,2019,Q3,10-Q,2019-07-31,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2018-04-01
17656,2018-06-30,5.326500e+10,0000320193-19-000119,2019,FY,10-K,2019-10-31,CY2018Q2,RevenueFromContractWithCustomerExcludingAssess...,USD,2018-04-01
17657,2018-09-29,2.655950e+11,0000320193-19-000119,2019,FY,10-K,2019-10-31,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2017-10-01
17658,2018-09-29,2.655950e+11,0000320193-20-000096,2020,FY,10-K,2020-10-30,CY2018,RevenueFromContractWithCustomerExcludingAssess...,USD,2017-10-01
17659,2018-09-29,6.290000e+10,0000320193-19-000119,2019,FY,10-K,2019-10-31,CY2018Q3,RevenueFromContractWithCustomerExcludingAssess...,USD,2018-07-01
17660,2018-12-29,8.431000e+10,0000320193-19-000010,2019,Q1,10-Q,2019-01-30,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2018-09-30
17661,2018-12-29,8.431000e+10,0000320193-19-000119,2019,FY,10-K,2019-10-31,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2018-09-30
17662,2018-12-29,8.431000e+10,0000320193-20-000010,2020,Q1,10-Q,2020-01-29,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2018-09-30
17663,2018-12-29,8.431000e+10,0000320193-20-000096,2020,FY,10-K,2020-10-30,CY2018Q4,RevenueFromContractWithCustomerExcludingAssess...,USD,2018-09-30
17664,2019-03-30,1.423250e+11,0000320193-19-000066,2019,Q2,10-Q,2019-05-01,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2018-09-30
17665,2019-03-30,1.423250e+11,0000320193-20-000052,2020,Q2,10-Q,2020-05-01,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2018-09-30
17666,2019-03-30,5.801500e+10,0000320193-19-000066,2019,Q2,10-Q,2019-05-01,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2018-12-30
17667,2019-03-30,5.801500e+10,0000320193-19-000119,2019,FY,10-K,2019-10-31,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2018-12-30
17668,2019-03-30,5.801500e+10,0000320193-20-000052,2020,Q2,10-Q,2020-05-01,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2018-12-30
17669,2019-03-30,5.801500e+10,0000320193-20-000096,2020,FY,10-K,2020-10-30,CY2019Q1,RevenueFromContractWithCustomerExcludingAssess...,USD,2018-12-30
17670,2019-06-29,1.961340e+11,0000320193-19-000076,2019,Q3,10-Q,2019-07-31,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2018-09-30
17671,2019-06-29,1.961340e+11,0000320193-20-000062,2020,Q3,10-Q,2020-07-31,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2018-09-30
17672,2019-06-29,5.380900e+10,0000320193-19-000076,2019,Q3,10-Q,2019-07-31,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2019-03-31
17673,2019-06-29,5.380900e+10,0000320193-19-000119,2019,FY,10-K,2019-10-31,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2019-03-31
17674,2019-06-29,5.380900e+10,0000320193-20-000062,2020,Q3,10-Q,2020-07-31,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2019-03-31
17675,2019-06-29,5.380900e+10,0000320193-20-000096,2020,FY,10-K,2020-10-30,CY2019Q2,RevenueFromContractWithCustomerExcludingAssess...,USD,2019-03-31
17676,2019-09-28,2.601740e+11,0000320193-19-000119,2019,FY,10-K,2019-10-31,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2018-09-30
17677,2019-09-28,2.601740e+11,0000320193-20-000096,2020,FY,10-K,2020-10-30,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2018-09-30
17678,2019-09-28,2.601740e+11,0000320193-21-000105,2021,FY,10-K,2021-10-29,CY2019,RevenueFromContractWithCustomerExcludingAssess...,USD,2018-09-30
17679,2019-09-28,6.404000e+10,0000320193-19-000119,2019,FY,10-K,2019-10-31,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2019-06-30
17680,2019-09-28,6.404000e+10,0000320193-20-000096,2020,FY,10-K,2020-10-30,CY2019Q3,RevenueFromContractWithCustomerExcludingAssess...,USD,2019-06-30
17681,2019-12-28,9.181900e+10,0000320193-20-000010,2020,Q1,10-Q,2020-01-29,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2019-09-29
17682,2019-12-28,9.181900e+10,0000320193-20-000096,2020,FY,10-K,2020-10-30,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2019-09-29
17683,2019-12-28,9.181900e+10,0000320193-21-000010,2021,Q1,10-Q,2021-01-28,CY2019Q4,RevenueFromContractWithCustomerExcludingAssess...,USD,2019-09-29
17684,2020-03-28,1.501320e+11,0000320193-20-000052,2020,Q2,10-Q,2020-05-01,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2019-09-29
17685,2020-03-28,1.501320e+11,0000320193-21-000056,2021,Q2,10-Q,2021-04-29,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2019-09-29
17686,2020-03-28,5.831300e+10,0000320193-20-000052,2020,Q2,10-Q,2020-05-01,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2019-12-29
17687,2020-03-28,5.831300e+10,0000320193-20-000096,2020,FY,10-K,2020-10-30,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2019-12-29
17688,2020-03-28,5.831300e+10,0000320193-21-000056,2021,Q2,10-Q,2021-04-29,CY2020Q1,RevenueFromContractWithCustomerExcludingAssess...,USD,2019-12-29
17689,2020-06-27,2.098170e+11,0000320193-20-000062,2020,Q3,10-Q,2020-07-31,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2019-09-29
17690,2020-06-27,2.098170e+11,0000320193-21-000065,2021,Q3,10-Q,2021-07-28,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2019-09-29
17691,2020-06-27,5.968500e+10,0000320193-20-000062,2020,Q3,10-Q,2020-07-31,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2020-03-29
17692,2020-06-27,5.968500e+10,0000320193-20-000096,2020,FY,10-K,2020-10-30,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2020-03-29
17693,2020-06-27,5.968500e+10,0000320193-21-000065,2021,Q3,10-Q,2021-07-28,CY2020Q2,RevenueFromContractWithCustomerExcludingAssess...,USD,2020-03-29
17694,2020-09-26,2.745150e+11,0000320193-20-000096,2020,FY,10-K,2020-10-30,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2019-09-29
17695,2020-09-26,2.745150e+11,0000320193-21-000105,2021,FY,10-K,2021-10-29,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2019-09-29
17696,2020-09-26,2.745150e+11,0000320193-22-000108,2022,FY,10-K,2022-10-28,CY2020,RevenueFromContractWithCustomerExcludingAssess...,USD,2019-09-29
17697,2020-09-26,6.469800e+10,0000320193-20-000096,2020,FY,10-K,2020-10-30,CY2020Q3,RevenueFromContractWithCustomerExcludingAssess...,USD,2020-06-28
17698,2020-12-26,1.114390e+11,0000320193-21-000010,2021,Q1,10-Q,2021-01-28,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2020-09-27
17699,2020-12-26,1.114390e+11,0000320193-22-000007,2022,Q1,10-Q,2022-01-28,CY2020Q4,RevenueFromContractWithCustomerExcludingAssess...,USD,2020-09-27
17700,2021-03-27,2.010230e+11,0000320193-21-000056,2021,Q2,10-Q,2021-04-29,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2020-09-27
17701,2021-03-27,2.010230e+11,0000320193-22-000059,2022,Q2,10-Q,2022-04-29,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2020-09-27
17702,2021-03-27,8.958400e+10,0000320193-21-000056,2021,Q2,10-Q,2021-04-29,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2020-12-27
17703,2021-03-27,8.958400e+10,0000320193-22-000059,2022,Q2,10-Q,2022-04-29,CY2021Q1,RevenueFromContractWithCustomerExcludingAssess...,USD,2020-12-27
17704,2021-06-26,2.824570e+11,0000320193-21-000065,2021,Q3,10-Q,2021-07-28,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2020-09-27
17705,2021-06-26,2.824570e+11,0000320193-22-000070,2022,Q3,10-Q,2022-07-29,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2020-09-27
17706,2021-06-26,8.143400e+10,0000320193-21-000065,2021,Q3,10-Q,2021-07-28,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2021-03-28
17707,2021-06-26,8.143400e+10,0000320193-22-000070,2022,Q3,10-Q,2022-07-29,CY2021Q2,RevenueFromContractWithCustomerExcludingAssess...,USD,2021-03-28
17708,2021-09-25,3.658170e+11,0000320193-21-000105,2021,FY,10-K,2021-10-29,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2020-09-27
17709,2021-09-25,3.658170e+11,0000320193-22-000108,2022,FY,10-K,2022-10-28,CY2021,RevenueFromContractWithCustomerExcludingAssess...,USD,2020-09-27
17710,2021-12-25,1.239450e+11,0000320193-22-000007,2022,Q1,10-Q,2022-01-28,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2021-09-26
17711,2021-12-25,1.239450e+11,0000320193-23-000006,2023,Q1,10-Q,2023-02-03,CY2021Q4,RevenueFromContractWithCustomerExcludingAssess...,USD,2021-09-26
17712,2022-03-26,2.212230e+11,0000320193-22-000059,2022,Q2,10-Q,2022-04-29,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2021-09-26
17713,2022-03-26,2.212230e+11,0000320193-23-000064,2023,Q2,10-Q,2023-05-05,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2021-09-26
17714,2022-03-26,9.727800e+10,0000320193-22-000059,2022,Q2,10-Q,2022-04-29,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2021-12-26
17715,2022-03-26,9.727800e+10,0000320193-23-000064,2023,Q2,10-Q,2023-05-05,CY2022Q1,RevenueFromContractWithCustomerExcludingAssess...,USD,2021-12-26
17716,2022-06-25,3.041820e+11,0000320193-22-000070,2022,Q3,10-Q,2022-07-29,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2021-09-26
17717,2022-06-25,8.295900e+10,0000320193-22-000070,2022,Q3,10-Q,2022-07-29,CY2022Q2,RevenueFromContractWithCustomerExcludingAssess...,USD,2022-03-27
17718,2022-09-24,3.943280e+11,0000320193-22-000108,2022,FY,10-K,2022-10-28,CY2022,RevenueFromContractWithCustomerExcludingAssess...,USD,2021-09-26
17719,2022-12-31,1.171540e+11,0000320193-23-000006,2023,Q1,10-Q,2023-02-03,CY2022Q4,RevenueFromContractWithCustomerExcludingAssess...,USD,2022-09-25
17720,2023-04-01,2.119900e+11,0000320193-23-000064,2023,Q2,10-Q,2023-05-05,NaN,RevenueFromContractWithCustomerExcludingAssess...,USD,2022-09-25
17721,2023-04-01,9.483600e+10,0000320193-23-000064,2023,Q2,10-Q,2023-05-05,CY2023Q1,RevenueFromContractWithCustomerExcludingAssess...,USD,2023-01-01
17722,2016-09-24,2.156390e+11,0000320193-18-000145,2018,FY,10-K,2018-11-05,CY2016,Revenues,USD,2015-09-27
17723,2016-12-31,7.835100e+10,0000320193-18-000145,2018,FY,10-K,2018-11-05,CY2016Q4,Revenues,USD,2016-09-25
17724,2017-04-01,5.289600e+10,0000320193-18-000145,2018,FY,10-K,2018-11-05,CY2017Q1,Revenues,USD,2017-01-01
17725,2017-07-01,4.540800e+10,0000320193-18-000145,2018,FY,10-K,2018-11-05,CY2017Q2,Revenues,USD,2017-04-02
17726,2017-09-30,2.292340e+11,0000320193-18-000145,2018,FY,10-K,2018-11-05,CY2017,Revenues,USD,2016-09-25
17727,2017-09-30,5.257900e+10,0000320193-18-000145,2018,FY,10-K,2018-11-05,CY2017Q3,Revenues,USD,2017-07-02
17728,2017-12-30,8.829300e+10,0000320193-18-000145,2018,FY,10-K,2018-11-05,CY2017Q4,Revenues,USD,2017-10-01
17729,2018-03-31,6.113700e+10,0000320193-18-000145,2018,FY,10-K,2018-11-05,CY2018Q1,Revenues,USD,2017-12-31
17730,2018-06-30,5.326500e+10,0000320193-18-000145,2018,FY,10-K,2018-11-05,CY2018Q2,Revenues,USD,2018-04-01
17731,2018-09-29,2.655950e+11,0000320193-18-000145,2018,FY,10-K,2018-11-05,CY2018,Revenues,USD,2017-10-01
17732,2018-09-29,6.290000e+10,0000320193-18-000145,2018,FY,10-K,2018-11-05,CY2018Q3,Revenues,USD,2018-07-01

In [428]:
jj[(jj.tag.isin(["MarketableSecuritiesCurrent", "MarketableSecurities"])) & (jj.form=='10-K') ]
#jj[jj.tag.isin(['NetCashProvidedByUsedInOperatingActivities','PaymentsToAcquirePropertyPlantAndEquipment'])]

,end,val,accn,fy,fp,form,filed,frame,tag,units,start
10784,2018-09-29,4.038800e+10,0000320193-19-000119,2019,FY,10-K,2019-10-31,CY2018Q3I,MarketableSecuritiesCurrent,USD,NaN
10788,2019-09-28,5.171300e+10,0000320193-19-000119,2019,FY,10-K,2019-10-31,NaN,MarketableSecuritiesCurrent,USD,NaN
10792,2019-09-28,5.171300e+10,0000320193-20-000096,2020,FY,10-K,2020-10-30,CY2019Q3I,MarketableSecuritiesCurrent,USD,NaN
10796,2020-09-26,5.292700e+10,0000320193-20-000096,2020,FY,10-K,2020-10-30,NaN,MarketableSecuritiesCurrent,USD,NaN
10800,2020-09-26,5.292700e+10,0000320193-21-000105,2021,FY,10-K,2021-10-29,CY2020Q3I,MarketableSecuritiesCurrent,USD,NaN
10804,2021-09-25,2.769900e+10,0000320193-21-000105,2021,FY,10-K,2021-10-29,NaN,MarketableSecuritiesCurrent,USD,NaN
10808,2021-09-25,2.769900e+10,0000320193-22-000108,2022,FY,10-K,2022-10-28,CY2021Q3I,MarketableSecuritiesCurrent,USD,NaN
10812,2022-09-24,2.465800e+10,0000320193-22-000108,2022,FY,10-K,2022-10-28,NaN,MarketableSecuritiesCurrent,USD,NaN

In [435]:
bs = eu.BalanceSheet(jj,2014)

In [436]:
bs.df

tag,AccountsReceivableNetCurrent,Assets,AssetsCurrent,CashAndCashEquivalentsAtCarryingValue,Goodwill,Liabilities,LiabilitiesAndStockholdersEquity,LiabilitiesCurrent,LongTermDebtNoncurrent,MarketableSecurities,StockholdersEquity
fy,,,,,,,,,,,
2014,1.746000e+10,2.318390e+11,6.853100e+10,1.384400e+10,4.616000e+09,1.202920e+11,2.318390e+11,6.344800e+10,NaN,NaN,1.115470e+11
2015,1.684900e+10,2.904790e+11,8.937800e+10,2.112000e+10,5.116000e+09,1.711240e+11,2.904790e+11,8.061000e+10,5.346300e+10,NaN,1.193550e+11
2016,1.575400e+10,3.216860e+11,1.068690e+11,2.048400e+10,5.414000e+09,1.934370e+11,3.216860e+11,7.900600e+10,7.542700e+10,NaN,1.282490e+11
2017,1.787400e+10,3.753190e+11,1.286450e+11,2.028900e+10,5.717000e+09,2.412720e+11,3.753190e+11,1.008140e+11,9.720700e+10,NaN,1.340470e+11
2018,2.318600e+10,3.657250e+11,1.313390e+11,2.591300e+10,NaN,2.585780e+11,3.657250e+11,1.168660e+11,9.373500e+10,NaN,1.071470e+11
2019,2.292600e+10,3.385160e+11,1.628190e+11,4.884400e+10,NaN,2.480280e+11,3.385160e+11,1.057180e+11,9.180700e+10,5.171300e+10,9.048800e+10
2020,1.612000e+10,3.238880e+11,1.437130e+11,3.801600e+10,NaN,2.585490e+11,3.238880e+11,1.053920e+11,9.866700e+10,5.292700e+10,6.533900e+10
2021,2.627800e+10,3.510020e+11,1.348360e+11,3.494000e+10,NaN,2.879120e+11,3.510020e+11,1.254810e+11,1.091060e+11,2.769900e+10,6.309000e+10
2022,2.818400e+10,3.527550e+11,1.354050e+11,2.364600e+10,NaN,3.020830e+11,3.527550e+11,1.539820e+11,9.895900e+10,2.465800e+10,5.067200e+10

In [196]:
pd.set_option('display.max_rows', None)

In [375]:
jj[(jj.tag.str.contains("MarketableSecurities")) &   (jj.form=='10-K')]
#jj[(jj.tag.str.contains("MarketableSecurities")) ]
#jj[jj.tag.isin(['NetCashProvidedByUsedInOperatingActivities','PaymentsToAcquirePropertyPlantAndEquipment'])]

,end,val,accn,fy,fp,form,filed,frame,tag,units,start
10784,2018-09-29,4.038800e+10,0000320193-19-000119,2019,FY,10-K,2019-10-31,CY2018Q3I,MarketableSecuritiesCurrent,USD,NaN
10788,2019-09-28,5.171300e+10,0000320193-19-000119,2019,FY,10-K,2019-10-31,NaN,MarketableSecuritiesCurrent,USD,NaN
10792,2019-09-28,5.171300e+10,0000320193-20-000096,2020,FY,10-K,2020-10-30,CY2019Q3I,MarketableSecuritiesCurrent,USD,NaN
10796,2020-09-26,5.292700e+10,0000320193-20-000096,2020,FY,10-K,2020-10-30,NaN,MarketableSecuritiesCurrent,USD,NaN
10800,2020-09-26,5.292700e+10,0000320193-21-000105,2021,FY,10-K,2021-10-29,CY2020Q3I,MarketableSecuritiesCurrent,USD,NaN
10804,2021-09-25,2.769900e+10,0000320193-21-000105,2021,FY,10-K,2021-10-29,NaN,MarketableSecuritiesCurrent,USD,NaN
10808,2021-09-25,2.769900e+10,0000320193-22-000108,2022,FY,10-K,2022-10-28,CY2021Q3I,MarketableSecuritiesCurrent,USD,NaN
10812,2022-09-24,2.465800e+10,0000320193-22-000108,2022,FY,10-K,2022-10-28,NaN,MarketableSecuritiesCurrent,USD,NaN
10820,2018-09-29,1.707990e+11,0000320193-19-000119,2019,FY,10-K,2019-10-31,CY2018Q3I,MarketableSecuritiesNoncurrent,USD,NaN
10824,2019-09-28,1.053410e+11,0000320193-19-000119,2019,FY,10-K,2019-10-31,NaN,MarketableSecuritiesNoncurrent,USD,NaN
10828,2019-09-28,1.053410e+11,0000320193-20-000096,2020,FY,10-K,2020-10-30,CY2019Q3I,MarketableSecuritiesNoncurrent,USD,NaN
10832,2020-09-26,1.008870e+11,0000320193-20-000096,2020,FY,10-K,2020-10-30,NaN,MarketableSecuritiesNoncurrent,USD,NaN
10836,2020-09-26,1.008870e+11,0000320193-21-000105,2021,FY,10-K,2021-10-29,CY2020Q3I,MarketableSecuritiesNoncurrent,USD,NaN
10840,2021-09-25,1.278770e+11,0000320193-21-000105,2021,FY,10-K,2021-10-29,NaN,MarketableSecuritiesNoncurrent,USD,NaN
10844,2021-09-25,1.278770e+11,0000320193-22-000108,2022,FY,10-K,2022-10-28,CY2021Q3I,MarketableSecuritiesNoncurrent,USD,NaN
10848,2022-09-24,1.208050e+11,0000320193-22-000108,2022,FY,10-K,2022-10-28,NaN,MarketableSecuritiesNoncurrent,USD,NaN

In [481]:
income = eu.IncomeStatement(jj,2014)

In [482]:
income.df

tag,EarningsPerShareDiluted,GrossProfit,NetIncomeLoss,OperatingExpenses,OperatingIncomeLoss,Revenues,SellingGeneralAndAdministrativeExpense,WeightedAverageNumberOfDilutedSharesOutstanding
fy,,,,,,,,
2014,6.45,7.053700e+10,3.951000e+10,1.803400e+10,5.250300e+10,NaN,1.199300e+10,6.122663e+09
2015,9.22,9.362600e+10,5.339400e+10,2.239600e+10,7.123000e+10,NaN,1.432900e+10,5.793069e+09
2016,8.31,8.426300e+10,4.568700e+10,2.423900e+10,6.002400e+10,2.156390e+11,1.419400e+10,5.500281e+09
2017,9.21,8.818600e+10,4.835100e+10,2.684200e+10,6.134400e+10,2.292340e+11,1.526100e+10,5.251692e+09
2018,2.98,1.018390e+11,5.953100e+10,3.094100e+10,7.089800e+10,2.655950e+11,1.670500e+10,2.000044e+10
2019,2.97,9.839200e+10,5.525600e+10,3.446200e+10,6.393000e+10,2.601740e+11,1.824500e+10,1.859565e+10
2020,3.28,1.049560e+11,5.741100e+10,3.866800e+10,6.628800e+10,2.745150e+11,1.991600e+10,1.752821e+10
2021,5.61,1.528360e+11,9.468000e+10,4.388700e+10,1.089490e+11,3.658170e+11,2.197300e+10,1.686492e+10
2022,6.11,1.707820e+11,9.980300e+10,5.134500e+10,1.194370e+11,3.943280e+11,2.509400e+10,1.632582e+10

In [415]:
rr = eu.filterStatement(jj)
ll = rr[rr.tag.isin(['RevenueFromContractWithCustomerExcludingAssessedTax','Revenues'])]
#pd.unique(ll[['val','fy']])
#pd.concat([ll['val'],ll['fy']]).unique()
ll
#ll.filter(items=['val', 'fy', 'tag']).drop_duplicates()

,end,val,accn,fy,fp,form,filed,frame,tag,units,start
17648,2017-09-30,2.292340e+11,0000320193-19-000119,2017,FY,10-K,2019-10-31,CY2017,RevenueFromContractWithCustomerExcludingAssess...,USD,2016-09-25
17658,2018-09-29,2.655950e+11,0000320193-20-000096,2018,FY,10-K,2020-10-30,CY2018,RevenueFromContractWithCustomerExcludingAssess...,USD,2017-10-01
17678,2019-09-28,2.601740e+11,0000320193-21-000105,2019,FY,10-K,2021-10-29,CY2019,RevenueFromContractWithCustomerExcludingAssess...,USD,2018-09-30
17696,2020-09-26,2.745150e+11,0000320193-22-000108,2020,FY,10-K,2022-10-28,CY2020,RevenueFromContractWithCustomerExcludingAssess...,USD,2019-09-29
17709,2021-09-25,3.658170e+11,0000320193-22-000108,2021,FY,10-K,2022-10-28,CY2021,RevenueFromContractWithCustomerExcludingAssess...,USD,2020-09-27
17718,2022-09-24,3.943280e+11,0000320193-22-000108,2022,FY,10-K,2022-10-28,CY2022,RevenueFromContractWithCustomerExcludingAssess...,USD,2021-09-26
17722,2016-09-24,2.156390e+11,0000320193-18-000145,2016,FY,10-K,2018-11-05,CY2016,Revenues,USD,2015-09-27
17726,2017-09-30,2.292340e+11,0000320193-18-000145,2017,FY,10-K,2018-11-05,CY2017,Revenues,USD,2016-09-25
17731,2018-09-29,2.655950e+11,0000320193-18-000145,2018,FY,10-K,2018-11-05,CY2018,Revenues,USD,2017-10-01

In [486]:
cashflow = eu.CashFlowStatement(jj,2014)

In [487]:
cashflow.df

tag,NetCashProvidedByUsedInOperatingActivities,PaymentsToAcquirePropertyPlantAndEquipment,ShareBasedCompensation
fy,,,
2014,NaN,9.571000e+09,2.863000e+09
2015,8.126600e+10,1.124700e+10,3.586000e+09
2016,6.623100e+10,1.273400e+10,4.210000e+09
2017,6.422500e+10,1.245100e+10,4.840000e+09
2018,7.743400e+10,1.331300e+10,5.340000e+09
2019,6.939100e+10,1.049500e+10,6.068000e+09
2020,8.067400e+10,7.309000e+09,6.829000e+09
2021,1.040380e+11,1.108500e+10,7.906000e+09
2022,1.221510e+11,1.070800e+10,9.038000e+09

In [459]:
mizrahi = eu.Mizrahi(bs, income,cashflow)

In [460]:
mizrahi.pretty()

In [489]:
threebrians = eu.ThreeBrians(bs, income, cashflow)
threebrians.pretty()