In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import datetime as datetime
import matplotlib.dates as mdates
import edgar_utils as eu

In [2]:
%load_ext autoreload
%autoreload 2

In [25]:
jj = eu.get_json_financials_from_tikr('KO')

        start         end   val                  accn    fy  fp  form  \
0  2008-01-01  2008-06-27  1.24  0001047469-09-007013  2009  Q2  10-Q
1  2008-03-29  2008-06-27  0.61  0001047469-09-007013  2009  Q2  10-Q
2  2009-01-01  2009-07-03  1.46  0001047469-09-007013  2009  Q2  10-Q
3  2009-04-04  2009-07-03  0.88  0001047469-09-007013  2009  Q2  10-Q

        filed     frame                      tag units
0  2009-07-30       NaN  EarningsPerShareDiluted  pure
1  2009-07-30  CY2008Q2  EarningsPerShareDiluted  pure
2  2009-07-30       NaN  EarningsPerShareDiluted  pure
3  2009-07-30  CY2009Q2  EarningsPerShareDiluted  pure
          start         end   val                  accn    fy  fp    form  \
0    2007-01-01  2007-12-31  2.57  0001047469-10-001476  2009  FY    10-K
1    2008-01-01  2008-09-26  2.06  0001047469-09-009321  2009  Q3  10-Q/A
2    2008-06-28  2008-09-26  0.81  0001047469-09-009321  2009  Q3  10-Q/A
3    2008-01-01  2008-12-31  2.49  0001047469-10-001476  2009  FY    10-K
4    2008-01-01  2008-12-31  2.49  0001047469-11-001506  2010  FY    10-K
..          ...         ...   ...                   ...   ...  ..     ...
182  2022-04-02  2022-07-01  0.44  0000021344-22-000034  2022  Q2    10-Q
183  2022-01-01  2022-09-30  1.73  0000021344-22-000042  2022  Q3    10-Q
184  2022-07-02  2022-09-30  0.65  0000021344-22-000042  2022  Q3    10-Q
185  2022-01-01  2022-12-31  2.19  0000021344-23-000011  2022  FY    10-K
186  2023-01-01  2023-03-31  0.72  0000021344-23-000024  2023  Q1    10-Q

          filed     frame                      tag       units
0    2010-02-26    CY2007  EarningsPerShareDiluted  USD/shares
1    2009-10-29       NaN  EarningsPerShareDiluted  USD/shares
2    2009-10-29  CY2008Q3  EarningsPerShareDiluted  USD/shares
3    2010-02-26       NaN  EarningsPerShareDiluted  USD/shares
4    2011-02-28    CY2008  EarningsPerShareDiluted  USD/shares
..          ...       ...                      ...         ...
182  2022-07-27  CY2022Q2  EarningsPerShareDiluted  USD/shares
183  2022-10-26       NaN  EarningsPerShareDiluted  USD/shares
184  2022-10-26  CY2022Q3  EarningsPerShareDiluted  USD/shares
185  2023-02-21    CY2022  EarningsPerShareDiluted  USD/shares
186  2023-04-26  CY2023Q1  EarningsPerShareDiluted  USD/shares

[187 rows x 11 columns]

In [244]:
bs = eu.BalanceSheet(jj,2014)

In [245]:
bs.df

tag,AccountsReceivableNetCurrent,Assets,AssetsCurrent,CashAndCashEquivalentsAtCarryingValue,Goodwill,InventoryNet,LiabilitiesAndStockholdersEquity,LiabilitiesCurrent,LongTermDebtNoncurrent,MarketableSecurities,StockholdersEquity
fy,,,,,,,,,,,
2014,4.466000e+09,9.202300e+10,3.298600e+10,8.958000e+09,1.210000e+10,3.100000e+09,9.202300e+10,3.237400e+10,1.906300e+10,3.665000e+09,3.032000e+10
2015,3.941000e+09,8.999600e+10,3.339500e+10,7.309000e+09,1.128900e+10,2.902000e+09,8.999600e+10,2.692900e+10,2.831100e+10,4.269000e+09,2.555400e+10
2016,3.856000e+09,8.727000e+10,3.401000e+10,8.555000e+09,1.062900e+10,2.675000e+09,8.727000e+10,2.653200e+10,2.968400e+10,4.051000e+09,2.306200e+10
2017,3.667000e+09,8.789600e+10,3.654500e+10,6.006000e+09,9.401000e+09,2.655000e+09,8.789600e+10,2.719400e+10,3.118200e+10,5.317000e+09,1.707200e+10
2018,3.685000e+09,8.321600e+10,2.493000e+10,9.077000e+09,1.410900e+10,3.071000e+09,8.321600e+10,2.878200e+10,2.537600e+10,5.013000e+09,1.698100e+10
2019,3.971000e+09,8.638100e+10,2.041100e+10,6.480000e+09,1.676400e+10,3.379000e+09,8.638100e+10,2.697300e+10,2.751600e+10,3.228000e+09,1.898100e+10
2020,3.144000e+09,8.729600e+10,1.924000e+10,6.795000e+09,1.750600e+10,3.266000e+09,8.729600e+10,1.460100e+10,4.012500e+10,2.348000e+09,1.929900e+10
2021,3.512000e+09,9.435400e+10,2.254500e+10,9.684000e+09,1.936300e+10,3.414000e+09,9.435400e+10,1.995000e+10,3.811600e+10,1.699000e+09,2.299900e+10
2022,3.487000e+09,9.276300e+10,2.259100e+10,9.519000e+09,1.878200e+10,4.233000e+09,9.276300e+10,1.972400e+10,3.637700e+10,1.069000e+09,2.410500e+10

In [131]:
jj.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25330 entries, 0 to 25329
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   end     25330 non-null  datetime64[ns]
 1   val     25330 non-null  float64
 2   accn    25330 non-null  object
 3   fy      25330 non-null  int64
 4   fp      25330 non-null  object
 5   form    25330 non-null  object
 6   filed   25330 non-null  datetime64[ns]
 7   frame   10540 non-null  object
 8   tag     25330 non-null  object
 9   units   25330 non-null  object
 10  start   16048 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(1), object(7)
memory usage: 2.1+ MB

In [239]:
kk=jj[(jj.tag.str.contains("InventoryNet"))  & (jj.form.isin(['10-K','8-K'])) & (jj.end.dt.year == jj.fy)]
#jj[(jj.tag.str.contains("MarketableSecurities")) ]
#jj[jj.tag.isin(['NetCashProvidedByUsedInOperatingActivities','PaymentsToAcquirePropertyPlantAndEquipment'])]

In [146]:
jj[(jj.tag.isin(["Revenues", "RevenueFromContractWithCustomerExcludingAssessedTax"])) & (jj.form=='10-K') ]

,end,val,accn,fy,fp,form,filed,frame,tag,units,start
21787,2016-12-31,4.186300e+10,0000021344-19-000014,2018,FY,10-K,2019-02-21,NaN,Revenues,USD,2016-01-01
21791,2017-12-31,3.541000e+10,0000021344-19-000014,2018,FY,10-K,2019-02-21,NaN,Revenues,USD,2017-01-01
21793,2017-12-31,3.621200e+10,0000021344-20-000006,2019,FY,10-K,2020-02-24,CY2017,Revenues,USD,2017-01-01
21801,2018-12-31,3.185600e+10,0000021344-19-000014,2018,FY,10-K,2019-02-21,NaN,Revenues,USD,2018-01-01
21803,2018-12-31,3.430000e+10,0000021344-20-000006,2019,FY,10-K,2020-02-24,NaN,Revenues,USD,2018-01-01
21804,2018-12-31,3.430000e+10,0000021344-21-000008,2020,FY,10-K,2021-02-25,CY2018,Revenues,USD,2018-01-01
21815,2019-12-31,3.726600e+10,0000021344-20-000006,2019,FY,10-K,2020-02-24,NaN,Revenues,USD,2019-01-01
21816,2019-12-31,3.726600e+10,0000021344-21-000008,2020,FY,10-K,2021-02-25,NaN,Revenues,USD,2019-01-01
21817,2019-12-31,3.726600e+10,0000021344-22-000009,2021,FY,10-K,2022-02-22,CY2019,Revenues,USD,2019-01-01
21828,2020-12-31,3.301400e+10,0000021344-21-000008,2020,FY,10-K,2021-02-25,NaN,Revenues,USD,2020-01-01
21829,2020-12-31,3.301400e+10,0000021344-22-000009,2021,FY,10-K,2022-02-22,NaN,Revenues,USD,2020-01-01
21830,2020-12-31,3.301400e+10,0000021344-23-000011,2022,FY,10-K,2023-02-21,CY2020,Revenues,USD,2020-01-01
21841,2021-12-31,3.865500e+10,0000021344-22-000009,2021,FY,10-K,2022-02-22,NaN,Revenues,USD,2021-01-01
21842,2021-12-31,3.865500e+10,0000021344-23-000011,2022,FY,10-K,2023-02-21,CY2021,Revenues,USD,2021-01-01
21849,2022-12-31,4.300400e+10,0000021344-23-000011,2022,FY,10-K,2023-02-21,CY2022,Revenues,USD,2022-01-01

In [143]:
jj[(jj.tag.isin(['OperatingIncomeLoss','NetIncomeLoss','EarningsPerShareDiluted', 'WeightedAverageNumberOfDilutedSharesOutstanding'])) & (jj.form=='10-K') & (jj.end.dt.year == jj.fy)]

,end,val,accn,fy,fp,form,filed,frame,tag,units,start
7446,2009-12-31,2.930000e+00,0001047469-10-001476,2009,FY,10-K,2010-02-26,NaN,EarningsPerShareDiluted,USD/shares,2009-01-01
7459,2010-12-31,5.060000e+00,0001047469-11-001506,2010,FY,10-K,2011-02-28,NaN,EarningsPerShareDiluted,USD/shares,2010-01-01
7473,2011-12-31,3.690000e+00,0000021344-12-000007,2011,FY,10-K,2012-02-23,NaN,EarningsPerShareDiluted,USD/shares,2011-01-01
7487,2012-12-31,1.970000e+00,0000021344-13-000007,2012,FY,10-K,2013-02-27,NaN,EarningsPerShareDiluted,USD/shares,2012-01-01
7501,2013-12-31,1.900000e+00,0000021344-14-000008,2013,FY,10-K,2014-02-27,NaN,EarningsPerShareDiluted,USD/shares,2013-01-01
7515,2014-12-31,1.600000e+00,0000021344-15-000005,2014,FY,10-K,2015-02-25,NaN,EarningsPerShareDiluted,USD/shares,2014-01-01
7529,2015-12-31,1.670000e+00,0000021344-16-000050,2015,FY,10-K,2016-02-25,NaN,EarningsPerShareDiluted,USD/shares,2015-01-01
7543,2016-12-31,1.490000e+00,0000021344-17-000009,2016,FY,10-K,2017-02-24,NaN,EarningsPerShareDiluted,USD/shares,2016-01-01
7557,2017-12-31,2.900000e-01,0000021344-18-000008,2017,FY,10-K,2018-02-23,NaN,EarningsPerShareDiluted,USD/shares,2017-01-01
7571,2018-12-31,1.500000e+00,0000021344-19-000014,2018,FY,10-K,2019-02-21,NaN,EarningsPerShareDiluted,USD/shares,2018-01-01
7585,2019-12-31,2.070000e+00,0000021344-20-000006,2019,FY,10-K,2020-02-24,NaN,EarningsPerShareDiluted,USD/shares,2019-01-01
7598,2020-12-31,1.790000e+00,0000021344-21-000008,2020,FY,10-K,2021-02-25,NaN,EarningsPerShareDiluted,USD/shares,2020-01-01
7611,2021-12-31,2.250000e+00,0000021344-22-000009,2021,FY,10-K,2022-02-22,NaN,EarningsPerShareDiluted,USD/shares,2021-01-01
7619,2022-12-31,2.190000e+00,0000021344-23-000011,2022,FY,10-K,2023-02-21,CY2022,EarningsPerShareDiluted,USD/shares,2022-01-01
14473,2009-12-31,6.824000e+09,0001047469-10-001476,2009,FY,10-K,2010-02-26,NaN,NetIncomeLoss,USD,2009-01-01
14486,2010-12-31,1.180900e+10,0001047469-11-001506,2010,FY,10-K,2011-02-28,NaN,NetIncomeLoss,USD,2010-01-01
14500,2011-12-31,8.572000e+09,0000021344-12-000007,2011,FY,10-K,2012-02-23,NaN,NetIncomeLoss,USD,2011-01-01
14514,2012-12-31,9.019000e+09,0000021344-13-000007,2012,FY,10-K,2013-02-27,NaN,NetIncomeLoss,USD,2012-01-01
14528,2013-12-31,8.584000e+09,0000021344-14-000008,2013,FY,10-K,2014-02-27,NaN,NetIncomeLoss,USD,2013-01-01
14542,2014-12-31,7.098000e+09,0000021344-15-000005,2014,FY,10-K,2015-02-25,NaN,NetIncomeLoss,USD,2014-01-01
14556,2015-12-31,7.351000e+09,0000021344-16-000050,2015,FY,10-K,2016-02-25,NaN,NetIncomeLoss,USD,2015-01-01
14570,2016-12-31,6.527000e+09,0000021344-17-000009,2016,FY,10-K,2017-02-24,NaN,NetIncomeLoss,USD,2016-01-01
14584,2017-12-31,1.248000e+09,0000021344-18-000008,2017,FY,10-K,2018-02-23,NaN,NetIncomeLoss,USD,2017-01-01
14598,2018-12-31,6.434000e+09,0000021344-19-000014,2018,FY,10-K,2019-02-21,NaN,NetIncomeLoss,USD,2018-01-01
14612,2019-12-31,8.920000e+09,0000021344-20-000006,2019,FY,10-K,2020-02-24,NaN,NetIncomeLoss,USD,2019-01-01
14625,2020-12-31,7.747000e+09,0000021344-21-000008,2020,FY,10-K,2021-02-25,NaN,NetIncomeLoss,USD,2020-01-01
14638,2021-12-31,9.771000e+09,0000021344-22-000009,2021,FY,10-K,2022-02-22,NaN,NetIncomeLoss,USD,2021-01-01
14646,2022-12-31,9.542000e+09,0000021344-23-000011,2022,FY,10-K,2023-02-21,CY2022,NetIncomeLoss,USD,2022-01-01
15076,2009-12-31,8.231000e+09,0001047469-10-001476,2009,FY,10-K,2010-02-26,NaN,OperatingIncomeLoss,USD,2009-01-01
15089,2010-12-31,8.449000e+09,0001047469-11-001506,2010,FY,10-K,2011-02-28,NaN,OperatingIncomeLoss,USD,2010-01-01
15103,2011-12-31,1.015400e+10,0000021344-12-000007,2011,FY,10-K,2012-02-23,NaN,OperatingIncomeLoss,USD,2011-01-01
15117,2012-12-31,1.077900e+10,0000021344-13-000007,2012,FY,10-K,2013-02-27,NaN,OperatingIncomeLoss,USD,2012-01-01
15131,2013-12-31,1.022800e+10,0000021344-14-000008,2013,FY,10-K,2014-02-27,NaN,OperatingIncomeLoss,USD,2013-01-01
15145,2014-12-31,9.708000e+09,0000021344-15-000005,2014,FY,10-K,2015-02-25,NaN,OperatingIncomeLoss,USD,2014-01-01
15159,2015-12-31,8.728000e+09,0000021344-16-000050,2015,FY,10-K,2016-02-25,NaN,OperatingIncomeLoss,USD,2015-01-01
15173,2016-12-31,8.626000e+09,0000021344-17-000009,2016,FY,10-K,2017-02-24,NaN,OperatingIncomeLoss,USD,2016-01-01
15187,2017-12-31,7.501000e+09,0000021344-18-000008,2017,FY,10-K,2018-02-23,NaN,OperatingIncomeLoss,USD,2017-01-01
15201,2018-12-31,8.700000e+09,0000021344-19-000014,2018,FY,10-K,2019-02-21,NaN,OperatingIncomeLoss,USD,2018-01-01
15215,2019-12-31,1.008600e+10,0000021344-20-000006,2019,FY,10-K,2020-02-24,NaN,OperatingIncomeLoss,USD,2019-01-01
15228,2020-12-31,8.997000e+09,0000021344-21-000008,2020,FY,10-K,2021-02-25,NaN,OperatingIncomeLoss,USD,2020-01-01
15241,2021-12-31,1.030800e+10,0000021344-22-000009,2021,FY,10-K,2022-02-22,NaN,OperatingIncomeLoss,USD,2021-01-01
15249,2022-12-31,1.090900e+10,0000021344-23-000011,2022,FY,10-K,2023-02-21,CY2022,OperatingIncomeLoss,USD,2022-01-01
24542,2009-12-31,2.329000e+09,0001047469-10-001476,2009,FY,10-K,2010-02-26,NaN,WeightedAverageNumberOfDilutedSharesOutstanding,shares,2009-01-01
24555,2010-12-31,2.333000e+09,0001047469-11-001506,2010,FY,10-K,2011-02-28,NaN,WeightedAverageNumberOfDilutedSharesOutstanding,shares,2010-01-01
24569,2011-12-31,2.323000e+09,0000021344-12-000007,2011,FY,10-K,2012-02-23,NaN,WeightedAverageNumberOfDilutedSharesOutstanding,shares,2011-01-01
24583,2012-12-31,4.584000e+09,0000021344-13-000007,2012,FY,10-K,2013-02-27,NaN,WeightedAverageNumberOfDilutedSharesOutstanding,shares,2012-01-01
24597,2013-12-31,4.509000e+09,0000021344-14-000008,2013,FY,10-K,2014-02-27,NaN,WeightedAverageNumberOfDilutedSharesOutstanding,shares,2013-01-01
24611,2014-12-31,4.450000e+09,0000021344-15-000005,2014,FY,10-K,2015-02-25,NaN,WeightedAverageNumberOfDilutedSharesOutstanding,shares,2014-01-01
24625,2015-12-31,4.405000e+09,0000021344-16-000050,2015,FY,10-K,2016-02-25,NaN,WeightedAverageNumberOfDilutedSharesOutstanding,shares,2015-01-01
24639,2016-12-31,4.367000e+09,0000021344-17-000009,2016,FY,10-K,2017-02-24,NaN,WeightedAverageNumberOfDilutedSharesOutstanding,shares,2016-01-01
24653,2017-12-31,4.324000e+09,0000021344-18-000008,2017,FY,10-K,2018-02-23,NaN,WeightedAverageNumberOfDilutedSharesOutstanding,shares,2017-01-01
24667,2018-12-31,4.299000e+09,0000021344-19-000014,2018,FY,10-K,2019-02-21,NaN,WeightedAverageNumberOfDilutedSharesOutstanding,shares,2018-01-01
24681,2019-12-31,4.314000e+09,0000021344-20-000006,2019,FY,10-K,2020-02-24,NaN,WeightedAverageNumberOfDilutedSharesOutstanding,shares,2019-01-01
24694,2020-12-31,4.323000e+09,0000021344-21-000008,2020,FY,10-K,2021-02-25,NaN,WeightedAverageNumberOfDilutedSharesOutstanding,shares,2020-01-01
24707,2021-12-31,4.340000e+09,0000021344-22-000009,2021,FY,10-K,2022-02-22,NaN,WeightedAverageNumberOfDilutedSharesOutstanding,shares,2021-01-01
24715,2022-12-31,4.350000e+09,0000021344-23-000011,2022,FY,10-K,2023-02-21,CY2022,WeightedAverageNumberOfDilutedSharesOutstanding,shares,2022-01-01

In [230]:
income = eu.IncomeStatement(jj,2014)

In [231]:
income.df

tag,EarningsPerShareDiluted,GrossProfit,IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest,IncomeTaxExpenseBenefit,InterestExpense,NetIncomeLoss,OperatingIncomeLoss,Revenues,SellingGeneralAndAdministrativeExpense,WeightedAverageNumberOfDilutedSharesOutstanding
fy,,,,,,,,,,
2014,1.60,2.810900e+10,9.325000e+09,2.201000e+09,4.830000e+08,7.098000e+09,9.708000e+09,NaN,1.721800e+10,4.450000e+09
2015,1.67,2.681200e+10,9.605000e+09,2.239000e+09,8.560000e+08,7.351000e+09,8.728000e+09,NaN,1.642700e+10,4.405000e+09
2016,1.49,2.539800e+10,8.136000e+09,1.586000e+09,7.330000e+08,6.527000e+09,8.657000e+09,4.186300e+10,1.537000e+10,4.367000e+09
2017,0.29,2.249100e+10,6.890000e+09,5.607000e+09,8.530000e+08,1.248000e+09,7.755000e+09,3.621200e+10,1.283400e+10,4.324000e+09
2018,1.50,2.123300e+10,8.225000e+09,1.749000e+09,9.500000e+08,6.434000e+09,9.152000e+09,3.430000e+10,1.100200e+10,4.299000e+09
2019,2.07,2.264700e+10,1.078600e+10,1.801000e+09,9.460000e+08,8.920000e+09,1.008600e+10,3.726600e+10,1.210300e+10,4.314000e+09
2020,1.79,1.958100e+10,9.749000e+09,1.981000e+09,1.437000e+09,7.747000e+09,8.997000e+09,3.301400e+10,9.731000e+09,4.323000e+09
2021,2.25,2.329800e+10,1.242500e+10,2.621000e+09,1.597000e+09,9.771000e+09,1.030800e+10,3.865500e+10,1.214400e+10,4.340000e+09
2022,2.19,2.500400e+10,1.168600e+10,2.115000e+09,8.820000e+08,9.542000e+09,1.090900e+10,4.300400e+10,1.288000e+10,4.350000e+09

In [232]:
cashflow = eu.CashFlowStatement(jj,2014)

In [218]:
cashflow.df

tag,DepreciationDepletionAndAmortization,NetCashProvidedByUsedInOperatingActivities,PaymentsToAcquirePropertyPlantAndEquipment,ShareBasedCompensation
fy,,,,
2014,1.976000e+09,1.061500e+10,2.406000e+09,209000000.0
2015,1.970000e+09,1.052800e+10,2.553000e+09,236000000.0
2016,1.787000e+09,8.792000e+09,2.262000e+09,258000000.0
2017,1.260000e+09,7.041000e+09,1.750000e+09,219000000.0
2018,1.086000e+09,7.627000e+09,1.548000e+09,225000000.0
2019,1.365000e+09,1.047100e+10,2.054000e+09,201000000.0
2020,1.536000e+09,9.844000e+09,1.177000e+09,126000000.0
2021,1.452000e+09,1.262500e+10,1.367000e+09,337000000.0
2022,1.260000e+09,1.101800e+10,1.484000e+09,356000000.0

In [116]:
mizrahi = eu.Mizrahi(bs, income, cashflow)

In [118]:
mizrahi.pretty()

In [175]:
threebrians = eu.ThreeBrians(bs, income, cashflow)
threebrians.pretty()

In [254]:
buffett = eu.Buffett(bs, income, cashflow)

In [257]:
buffett.report_qualitative()

,GrossMargin,R&D,NPM,SGA,InterestExpense,DepreciationAmortizationExpense,IncomeTaxScrutiny,Asset Sale - Entry Other,Inventory,NetReceivables
fy,,,,,,,,,,
2014,nan,Too Much R&D? tbd,nan,May be OK; Sometimes necessary to keep DCA,Little to no interest expense; great!,Higher depreciation % => may have no DCA,Tax gap may be too wide!,Asset Sale: Look for Entry other? TBD,Is Inventory going up alongside Net Income?,Is Receivables/Sales trending down? This indic...
2015,nan,Too Much R&D? tbd,nan,May be OK; Sometimes necessary to keep DCA,Little to no interest expense; great!,Higher depreciation % => may have no DCA,Tax gap may be too wide!,Asset Sale: Look for Entry other? TBD,Is Inventory going up alongside Net Income?,Is Receivables/Sales trending down? This indic...
2016,Gross Margin implies DCA,Too Much R&D? tbd,NPM implies grey area; may or may have some DCA,May be OK; Sometimes necessary to keep DCA,Little to no interest expense; great!,Higher depreciation % => may have no DCA,Tax gap may be too wide!,Asset Sale: Look for Entry other? TBD,Is Inventory going up alongside Net Income?,Is Receivables/Sales trending down? This indic...
2017,Gross Margin implies DCA,Too Much R&D? tbd,NPM implies highly competitive industry; hard ...,May be OK; Sometimes necessary to keep DCA,Company may have tough competition,Higher depreciation % => may have no DCA,Tax gap may be too wide!,Asset Sale: Look for Entry other? TBD,Is Inventory going up alongside Net Income?,Is Receivables/Sales trending down? This indic...
2018,Gross Margin implies DCA,Too Much R&D? tbd,NPM implies grey area; may or may have some DCA,May be OK; Sometimes necessary to keep DCA,Company may have tough competition,Higher depreciation % => may have no DCA,Taxes seem good,Asset Sale: Look for Entry other? TBD,Is Inventory going up alongside Net Income?,Is Receivables/Sales trending down? This indic...
2019,Gross Margin implies DCA,Too Much R&D? tbd,NPM implies DCA,May be OK; Sometimes necessary to keep DCA,Little to no interest expense; great!,Higher depreciation % => may have no DCA,Tax gap may be too wide!,Asset Sale: Look for Entry other? TBD,Is Inventory going up alongside Net Income?,Is Receivables/Sales trending down? This indic...
2020,Gross Margin implies DCA,Too Much R&D? tbd,NPM implies DCA,May be OK; Sometimes necessary to keep DCA,Company may have tough competition,Higher depreciation % => may have no DCA,Taxes seem good,Asset Sale: Look for Entry other? TBD,Is Inventory going up alongside Net Income?,Is Receivables/Sales trending down? This indic...
2021,Gross Margin implies DCA,Too Much R&D? tbd,NPM implies DCA,May be OK; Sometimes necessary to keep DCA,Company may have tough competition,Higher depreciation % => may have no DCA,Taxes seem good,Asset Sale: Look for Entry other? TBD,Is Inventory going up alongside Net Income?,Is Receivables/Sales trending down? This indic...
2022,Gross Margin implies DCA,Too Much R&D? tbd,NPM implies DCA,May be OK; Sometimes necessary to keep DCA,Little to no interest expense; great!,Higher depreciation % => may have no DCA,Tax gap may be too wide!,Asset Sale: Look for Entry other? TBD,Is Inventory going up alongside Net Income?,Is Receivables/Sales trending down? This indic...

In [258]:
buffett.report_quantitative()

,GrossMargin,R&D,NPM,SGA,InterestExpense,DepreciationAmortizationExpense,IncomeTaxManualCalc,ReportedTax,EPS-DILUTED,EPS_YoY,EBT,Inventory,NetReceivables
fy,,,,,,,,,,,,,
2014,NaN,tbd,NaN,0.612544,0.049753,0.203543,1.958250e+09,2.201000e+09,1.60,NaN,9.325000e+09,3.100000e+09,NaN
2015,NaN,tbd,NaN,0.612673,0.098075,0.225710,2.017050e+09,2.239000e+09,1.67,0.043750,9.605000e+09,2.902000e+09,NaN
2016,0.606693,tbd,0.155913,0.605166,0.084671,0.206423,1.708560e+09,1.586000e+09,1.49,-0.107784,8.136000e+09,2.675000e+09,0.092110
2017,0.621092,tbd,0.034464,0.570628,0.109994,0.162476,1.446900e+09,5.607000e+09,0.29,-0.805369,6.890000e+09,2.655000e+09,0.101265
2018,0.619038,tbd,0.187580,0.518156,0.103802,0.118663,1.727250e+09,1.749000e+09,1.50,4.172414,8.225000e+09,3.071000e+09,0.107434
2019,0.607712,tbd,0.239360,0.534420,0.093793,0.135336,2.265060e+09,1.801000e+09,2.07,0.380000,1.078600e+10,3.379000e+09,0.106558
2020,0.593112,tbd,0.234658,0.496961,0.159720,0.170724,2.047290e+09,1.981000e+09,1.79,-0.135266,9.749000e+09,3.266000e+09,0.095232
2021,0.602716,tbd,0.252775,0.521246,0.154928,0.140861,2.609250e+09,2.621000e+09,2.25,0.256983,1.242500e+10,3.414000e+09,0.090855
2022,0.581434,tbd,0.221886,0.515118,0.080851,0.115501,2.454060e+09,2.115000e+09,2.19,-0.026667,1.168600e+10,4.233000e+09,0.081085